### ISSUE TITLE
Extract dataset for the shiny

### ISSUE THREAD

**Issue by cedricbriandgithub** [mariazti/Shiny_results#3]
# type of data

Silver eel number
Silver eel number R
Silver eel number W
Silver eel biomass
Male silver eel number
Female silver eel numbers

Yellow eel number
Yellow eel average density ?
Yellow eel density at the sea ?
Yellow eel biomass

# zones

whole area (3 countries)
Sudoe area
country
zone
basin

**Comment by mariazti** [comment]
Presence probability of yellow eel?

For the GT1 tab (observed eel data), we must extract data from electrofishing:
Number and density Yellow eel
Number and density Silver eel

**Comment by cedricbriandgithub** [comment]
![electrofishing_method](https://user-images.githubusercontent.com/26055877/105506438-57231c00-5cca-11eb-88ed-b1dbd98017d8.png)
![electrofishing_method](https://user-images.githubusercontent.com/26055877/105506454-5b4f3980-5cca-11eb-8a8c-671b66f1beaa.png)
this is a ggplot, I say we make that leaflet , what info do we show ?
Data provider
method
size according to density
observed size strucutre if available ?
